import type { CreativeCard, CreativeIntent, ProductCategory } from '../types/index';

// BFL Creative Studio — Creative Library
// 82 cards · reach-weighted CTR from Meta campaign data
// Pre-filter: classifyProduct() + getTopCreatives()

export const creativeLibrary: CreativeCard[] = [
  {
    filename: "Card_on_Center_Stage_with_Card_Benifits.png",
    display_name: "Card on Center Stage — Card Benefits",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 2.84,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density", "emi_per_month", "affordability_messaging"],
    url: "/creatives/Card_on_Center_Stage_with_Card_Benifits.png",
  },
  {
    filename: "Card_on_Center_Stage_with_Card_Benifits_1.png",
    display_name: "Card on Center Stage — Benefits v2 (5.49%)",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 5.49,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density", "emi_per_month", "affordability_messaging"],
    url: "/creatives/Card_on_Center_Stage_with_Card_Benifits_1.png",
  },
  {
    filename: "Card_Specific_with_Card_Benifits.png",
    display_name: "Card Specific — Benefits Highlight (4.46%)",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 4.46,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density", "affordability_messaging"],
    url: "/creatives/Card_Specific_with_Card_Benifits.png",
  },
  {
    filename: "Card_In_Center_with_Card_Benifits.png",
    display_name: "Card in Center — Core Benefits (4.03%)",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 4.03,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density", "affordability_messaging"],
    url: "/creatives/Card_In_Center_with_Card_Benifits.png",
  },
  {
    filename: "Card_In_Center_stage_with_Card_Benifits.png",
    display_name: "Card in Center Stage — Benefits",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 3.84,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density", "affordability_messaging"],
    url: "/creatives/Card_In_Center_stage_with_Card_Benifits.png",
  },
  {
    filename: "Card_In_Center_with_Card_Benifits_1.png",
    display_name: "Card in Center — Benefits v2",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led"],
    reach_weighted_ctr: 1.05,
    key_features: ["card_visible", "loan_limit_shown", "affordability_messaging"],
    url: "/creatives/Card_In_Center_with_Card_Benifits_1.png",
  },
  {
    filename: "Festive_Card_Benefits.png",
    display_name: "Festive Card Benefits — Savings Season (5.06%)",
    creative_type: "Festive",
    product_category: "Card",
    goal_fit: ["Festive/Event"],
    reach_weighted_ctr: 5.06,
    key_features: ["festive_theme", "cashback_visible", "card_visible", "loan_limit_shown", "high_text_density"],
    url: "/creatives/Festive_Card_Benefits.png",
  },
  {
    filename: "Washing_Machine_with_Festive_Card_Benifits.png",
    display_name: "Washing Machine — Festive + ₹2K Cashback (5.29%)",
    creative_type: "Festive",
    product_category: "Washing Machine",
    goal_fit: ["Festive/Event", "Product-Led"],
    reach_weighted_ctr: 5.29,
    key_features: ["festive_theme", "cashback_visible", "card_visible", "loan_limit_shown", "high_text_density", "single_product"],
    url: "/creatives/Washing_Machine_with_Festive_Card_Benifits.png",
  },
  {
    filename: "Refrigerator_with_Festive_Card_Benfits.png",
    display_name: "Refrigerator — Festive + ₹2K Cashback (4.54%)",
    creative_type: "Festive",
    product_category: "Refrigerator",
    goal_fit: ["Festive/Event", "Product-Led"],
    reach_weighted_ctr: 4.54,
    key_features: ["festive_theme", "cashback_visible", "card_visible", "loan_limit_shown", "high_text_density", "single_product"],
    url: "/creatives/Refrigerator_with_Festive_Card_Benfits.png",
  },
  {
    filename: "TV_and_Card_with_Festive_Card_Benefits.png",
    display_name: "Smart TV — Festive + Card Benefits (4.63%)",
    creative_type: "Festive",
    product_category: "TV",
    goal_fit: ["Festive/Event", "Product-Led"],
    reach_weighted_ctr: 4.63,
    key_features: ["festive_theme", "cashback_visible", "card_visible", "loan_limit_shown", "high_text_density", "single_product"],
    url: "/creatives/TV_and_Card_with_Festive_Card_Benefits.png",
  },
  {
    filename: "TV_with_Festive_Card_Benefits.png",
    display_name: "Smart TV — Festive Benefits",
    creative_type: "Festive",
    product_category: "TV",
    goal_fit: ["Festive/Event", "Product-Led"],
    reach_weighted_ctr: 3.71,
    key_features: ["festive_theme", "card_visible", "loan_limit_shown", "single_product"],
    url: "/creatives/TV_with_Festive_Card_Benefits.png",
  },
  {
    filename: "Google_Pixel_with_Card_and_Festive_Card_Benifits.png",
    display_name: "Google Pixel — Festive + ₹2K Cashback",
    creative_type: "Festive",
    product_category: "Smartphone",
    goal_fit: ["Festive/Event", "Product-Led"],
    reach_weighted_ctr: 2.94,
    key_features: ["festive_theme", "cashback_visible", "card_visible", "loan_limit_shown", "brand_logo", "single_product"],
    url: "/creatives/Google_Pixel_with_Card_and_Festive_Card_Benifits.png",
  },
  {
    filename: "Amazon_500_Gift_Card.png",
    display_name: "Amazon ₹500 Gift Card — Offer Lead (3.94%)",
    creative_type: "Offer Highlight",
    product_category: "Card",
    goal_fit: ["Offer-Led", "Card-Led"],
    reach_weighted_ctr: 3.94,
    key_features: ["cashback_visible", "card_visible", "loan_limit_shown", "high_text_density", "affordability_messaging"],
    url: "/creatives/Amazon_500_Gift_Card.png",
  },
  {
    filename: "11k_Offer_brands_Card_image.png",
    display_name: "11K Offer — Multi-Brand Partner Benefits",
    creative_type: "Offer Highlight",
    product_category: "Card",
    goal_fit: ["Offer-Led", "Card-Led"],
    reach_weighted_ctr: 3.32,
    key_features: ["cashback_visible", "card_visible", "partner_logo", "high_text_density", "loan_limit_shown"],
    url: "/creatives/11k_Offer_brands_Card_image.png",
  },
  {
    filename: "AC_with_Card_Benifits.png",
    display_name: "AC — Card Benefits Highlight (3.93%)",
    creative_type: "Offer Highlight",
    product_category: "AC",
    goal_fit: ["Offer-Led", "Product-Led"],
    reach_weighted_ctr: 3.93,
    key_features: ["card_visible", "cashback_visible", "high_text_density", "loan_limit_shown"],
    url: "/creatives/AC_with_Card_Benifits.png",
  },
  {
    filename: "Card_in_Center_with_Flipkart_Specific_Card_Benefits.png",
    display_name: "Flipkart + Card — BBD Exclusive Benefits (6.03%)",
    creative_type: "Partner Co-branded",
    product_category: "Card",
    goal_fit: ["Festive/Event", "Offer-Led"],
    reach_weighted_ctr: 6.03,
    key_features: ["partner_logo", "card_visible", "cashback_visible", "festive_theme", "loan_limit_shown", "high_text_density"],
    url: "/creatives/Card_in_Center_with_Flipkart_Specific_Card_Benefits.png",
  },
  {
    filename: "Flipkart_Electronic_Cluster_with_Card_Benefits.png",
    display_name: "Flipkart Electronics Cluster — BBD (4.15%)",
    creative_type: "Partner Co-branded",
    product_category: "Electronics Cluster",
    goal_fit: ["Festive/Event", "Product-Led"],
    reach_weighted_ctr: 4.15,
    key_features: ["partner_logo", "festive_theme", "card_visible", "cashback_visible", "multi_product"],
    url: "/creatives/Flipkart_Electronic_Cluster_with_Card_Benefits.png",
  },
  {
    filename: "Flipkart_and_OnePlus_Product_with_Card_and_Benifits.png",
    display_name: "Flipkart + OnePlus — Partner Benefits (3.79%)",
    creative_type: "Partner Co-branded",
    product_category: "Smartphone",
    goal_fit: ["Product-Led", "Offer-Led"],
    reach_weighted_ctr: 3.79,
    key_features: ["partner_logo", "card_visible", "cashback_visible", "brand_logo", "single_product", "emi_per_month"],
    url: "/creatives/Flipkart_and_OnePlus_Product_with_Card_and_Benifits.png",
  },
  {
    filename: "Flipkart_Specific_Products_with_Card_and_Exclusive_Benifits.png",
    display_name: "Flipkart — Exclusive Card Benefits",
    creative_type: "Partner Co-branded",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led", "Offer-Led"],
    reach_weighted_ctr: 2.72,
    key_features: ["partner_logo", "card_visible", "cashback_visible", "high_text_density"],
    url: "/creatives/Flipkart_Specific_Products_with_Card_and_Exclusive_Benifits.png",
  },
  {
    filename: "Volatas_AC_Benefits_Card_Image.png",
    display_name: "Voltas AC — Lifestyle with Card Benefits (4.56%)",
    creative_type: "Lifestyle",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 4.56,
    key_features: ["lifestyle_person", "card_visible", "brand_logo", "emi_per_month", "high_text_density", "single_product"],
    url: "/creatives/Volatas_AC_Benefits_Card_Image.png",
  },
  {
    filename: "LG_AC_Benefits_10k_Cashback.png",
    display_name: "LG AC — Lifestyle + ₹10K Cashback",
    creative_type: "Lifestyle",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.84,
    key_features: ["lifestyle_person", "cashback_visible", "brand_logo", "emi_per_month", "high_text_density", "single_product"],
    url: "/creatives/LG_AC_Benefits_10k_Cashback.png",
  },
  {
    filename: "LG_Voltas_AC_carousel.png",
    display_name: "LG & Voltas AC Carousel — ₹1K Cashback",
    creative_type: "Partner Co-branded",
    product_category: "AC",
    goal_fit: ["Product-Led", "Offer-Led"],
    reach_weighted_ctr: 1.46,
    key_features: ["multi_product", "cashback_visible", "brand_logo", "emi_per_month", "partner_logo"],
    url: "/creatives/LG_Voltas_AC_carousel.png",
  },
  {
    filename: "Google_Pixel_with_Card_and_Card_Benifits.png",
    display_name: "Google Pixel — Card + Benefits (3.60%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 3.6,
    key_features: ["card_visible", "cashback_visible", "brand_logo", "loan_limit_shown", "single_product", "high_text_density"],
    url: "/creatives/Google_Pixel_with_Card_and_Card_Benifits.png",
  },
  {
    filename: "Oppo_A6_pro_Product_with_Card_and_Benifits.png",
    display_name: "Oppo A6 Pro — Product + EMI (4.88%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 4.88,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "cashback_visible", "single_product", "high_text_density"],
    url: "/creatives/Oppo_A6_pro_Product_with_Card_and_Benifits.png",
  },
  {
    filename: "Oppo_A6x_Product_with_Card_Benifits.png",
    display_name: "Oppo A6x — Product Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 3.3,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Oppo_A6x_Product_with_Card_Benifits.png",
  },
  {
    filename: "Oppo_Reno_15c_with_Card_and_Benifits.png",
    display_name: "Oppo Reno 15C — Product + Card",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 3.35,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Oppo_Reno_15c_with_Card_and_Benifits.png",
  },
  {
    filename: "Oppo_A5.png",
    display_name: "Oppo A5 — Product Spotlight",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.15,
    key_features: ["brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Oppo_A5.png",
  },
  {
    filename: "Oppo_Phone_Specific_with_Card_on_Center_Right_and_Card_Benifits.png",
    display_name: "Oppo Phone — Card Center Right",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.1,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Oppo_Phone_Specific_with_Card_on_Center_Right_and_Card_Benifits.png",
  },
  {
    filename: "Samsung_Phone_with_Card.png",
    display_name: "Samsung Phone — Clean Product + EMI (4.63%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 4.63,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "loan_limit_shown", "single_product", "high_text_density"],
    url: "/creatives/Samsung_Phone_with_Card.png",
  },
  {
    filename: "Samsung_S25_Ultra_with_Card_and_Card_Benefits.png",
    display_name: "Samsung S25 Ultra — Card + Benefits (2.80%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.8,
    key_features: ["card_visible", "cashback_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Samsung_S25_Ultra_with_Card_and_Card_Benefits.png",
  },
  {
    filename: "Samsung__with_Card_and_Card_Benefits.png",
    display_name: "Samsung — Card Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.02,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Samsung__with_Card_and_Card_Benefits.png",
  },
  {
    filename: "Samsung_Phones_with_Card_Benefits.png",
    display_name: "Samsung Phones — Card Benefits (2.93%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.93,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "loan_limit_shown", "single_product", "high_text_density"],
    url: "/creatives/Samsung_Phones_with_Card_Benefits.png",
  },
  {
    filename: "Samsung_Fold__Flip_with_Card_Benefits.png",
    display_name: "Samsung Fold & Flip — Card Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.7,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Samsung_Fold__Flip_with_Card_Benefits.png",
  },
  {
    filename: "Apple_IPhone_with_Card_in_Center_and_Card_Benifits.png",
    display_name: "Apple iPhone — Card Center + Benefits (2.13%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.13,
    key_features: ["card_visible", "cashback_visible", "brand_logo", "loan_limit_shown", "single_product", "high_text_density"],
    url: "/creatives/Apple_IPhone_with_Card_in_Center_and_Card_Benifits.png",
  },
  {
    filename: "Apple_IPhone_with_Card_Benifits.png",
    display_name: "Apple iPhone — Card Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.49,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Apple_IPhone_with_Card_Benifits.png",
  },
  {
    filename: "Apple_IPhone_with_Card_Benefits_Gift.png",
    display_name: "Apple iPhone — Zero Down + Cashback Gift",
    creative_type: "Offer Highlight",
    product_category: "Smartphone",
    goal_fit: ["Offer-Led", "Product-Led"],
    reach_weighted_ctr: 1.84,
    key_features: ["cashback_visible", "card_visible", "brand_logo", "affordability_messaging", "single_product"],
    url: "/creatives/Apple_IPhone_with_Card_Benefits_Gift.png",
  },
  {
    filename: "Apple_Iphone_Cluster_with_Card_in_Center.png",
    display_name: "Apple iPhone Cluster — Card Center",
    creative_type: "Card Spotlight",
    product_category: "Smartphone",
    goal_fit: ["Card-Led", "Product-Led"],
    reach_weighted_ctr: 1.61,
    key_features: ["card_visible", "brand_logo", "multi_product"],
    url: "/creatives/Apple_Iphone_Cluster_with_Card_in_Center.png",
  },
  {
    filename: "Apple_Iphone_Products_with_Card_Benifits.png",
    display_name: "Apple iPhone Lineup — EMI + Card",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.24,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "affordability_messaging", "multi_product"],
    url: "/creatives/Apple_Iphone_Products_with_Card_Benifits.png",
  },
  {
    filename: "Apple_IPhone_Specific_Carousel.png",
    display_name: "Apple iPhone 15/16 Carousel",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.22,
    key_features: ["brand_logo", "emi_per_month", "multi_product"],
    url: "/creatives/Apple_IPhone_Specific_Carousel.png",
  },
  {
    filename: "Apple_Iphone_Carousel_with_EMI_options.png",
    display_name: "Apple iPhone Carousel — EMI Options",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.23,
    key_features: ["brand_logo", "emi_per_month", "multi_product", "affordability_messaging"],
    url: "/creatives/Apple_Iphone_Carousel_with_EMI_options.png",
  },
  {
    filename: "Apple_Iphone_Carousel_with_EMI_options_light.png",
    display_name: "Apple iPhone Carousel — EMI Options Light",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.17,
    key_features: ["brand_logo", "emi_per_month", "multi_product"],
    url: "/creatives/Apple_Iphone_Carousel_with_EMI_options_light.png",
  },
  {
    filename: "Apple_IPhone_Carousel.png",
    display_name: "Apple iPhone 17/16 Carousel — Get Card",
    creative_type: "Card Spotlight",
    product_category: "Smartphone",
    goal_fit: ["Card-Led", "Product-Led"],
    reach_weighted_ctr: 1.38,
    key_features: ["card_visible", "brand_logo", "multi_product", "affordability_messaging"],
    url: "/creatives/Apple_IPhone_Carousel.png",
  },
  {
    filename: "Iphone_16E_with_Benefits.png",
    display_name: "iPhone 16e — Built for Apple Intelligence",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.44,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "loan_limit_shown", "single_product", "high_text_density"],
    url: "/creatives/Iphone_16E_with_Benefits.png",
  },
  {
    filename: "Vivo_X200_FE_with_Card_EMI_Benefits.png",
    display_name: "Vivo X200 FE — EMI Benefits (2.68%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.68,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Vivo_X200_FE_with_Card_EMI_Benefits.png",
  },
  {
    filename: "Vivo_Phone_with_Card_Benefits.png",
    display_name: "Vivo Phone — Card Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.05,
    key_features: ["brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Vivo_Phone_with_Card_Benefits.png",
  },
  {
    filename: "Vivo_Phone_with_Card_Benefits_1.png",
    display_name: "Vivo Phone — Card Benefits v2 (2.19%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.19,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Vivo_Phone_with_Card_Benefits_1.png",
  },
  {
    filename: "Vivo_X300_Phone_with_Card_EMI_Benefits.png",
    display_name: "Vivo X300 — EMI Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.28,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Vivo_X300_Phone_with_Card_EMI_Benefits.png",
  },
  {
    filename: "Realme_16_Pro_Phone_with_Product_Specific_Card_Benefits.png",
    display_name: "Realme 16 Pro — Card Benefits (2.67%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.67,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Realme_16_Pro_Phone_with_Product_Specific_Card_Benefits.png",
  },
  {
    filename: "Redmi_Note_15_Pro_Phone_with_Product_Specific_Card_Benefits.png",
    display_name: "Redmi Note 15 Pro — Card Benefits (2.86%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.86,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Redmi_Note_15_Pro_Phone_with_Product_Specific_Card_Benefits.png",
  },
  {
    filename: "Redmi_Note_15C_Phone_with_Product_Specific_Card_Benefits.png",
    display_name: "Redmi Note 15C — Card Benefits (2.65%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.65,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Redmi_Note_15C_Phone_with_Product_Specific_Card_Benefits.png",
  },
  {
    filename: "OnePlus_15_with_Card_Benifits.png",
    display_name: "OnePlus 15 — Card Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.89,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/OnePlus_15_with_Card_Benifits.png",
  },
  {
    filename: "Phone_Carousel_with_Card.png",
    display_name: "Samsung + OnePlus Phone Carousel",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.25,
    key_features: ["emi_per_month", "multi_product", "brand_logo"],
    url: "/creatives/Phone_Carousel_with_Card.png",
  },
  {
    filename: "Vivo_Samsung_Carousel_Benefits.png",
    display_name: "Vivo + Samsung Phone Carousel — Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.14,
    key_features: ["cashback_visible", "multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/Vivo_Samsung_Carousel_Benefits.png",
  },
  {
    filename: "Oppo_Samsung_Phone_Carousel.png",
    display_name: "Oppo + Samsung Phone Carousel — Cashback",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.34,
    key_features: ["cashback_visible", "multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/Oppo_Samsung_Phone_Carousel.png",
  },
  {
    filename: "Vivo_Samsung_Carousel_Benefits_1.png",
    display_name: "Vivo + Samsung Carousel — Card Visible",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.49,
    key_features: ["card_visible", "cashback_visible", "multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/Vivo_Samsung_Carousel_Benefits_1.png",
  },
  {
    filename: "Phone_Carousel_with_Card_Benefits.png",
    display_name: "Phone Carousel — Card Benefits",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.02,
    key_features: ["card_visible", "multi_product", "brand_logo"],
    url: "/creatives/Phone_Carousel_with_Card_Benefits.png",
  },
  {
    filename: "Ipad_Colours_with_Cards.png",
    display_name: "iPad Colours — EMI + Card (3.95%)",
    creative_type: "Product Moment",
    product_category: "Tablet",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 3.95,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "multi_product"],
    url: "/creatives/Ipad_Colours_with_Cards.png",
  },
  {
    filename: "Apple_IPad_Products_with_Card.png",
    display_name: "Apple iPad — Products with Card (3.00%)",
    creative_type: "Product Moment",
    product_category: "Tablet",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 3.0,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "multi_product"],
    url: "/creatives/Apple_IPad_Products_with_Card.png",
  },
  {
    filename: "Apple_IPad_Products_with_Card_with_Brands.png",
    display_name: "Apple iPad — Products + Partner Brands",
    creative_type: "Product Moment",
    product_category: "Tablet",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.83,
    key_features: ["brand_logo", "emi_per_month", "multi_product", "partner_logo"],
    url: "/creatives/Apple_IPad_Products_with_Card_with_Brands.png",
  },
  {
    filename: "Multiple_Laptop_Specific_with_Card.png",
    display_name: "Multiple Laptops — EMI Options (3.20%)",
    creative_type: "Product Moment",
    product_category: "Laptop",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 3.2,
    key_features: ["card_visible", "emi_per_month", "multi_product", "high_text_density"],
    url: "/creatives/Multiple_Laptop_Specific_with_Card.png",
  },
  {
    filename: "Laptop_Specific_with_Card.png",
    display_name: "Single Laptop — EMI + Card (2.51%)",
    creative_type: "Product Moment",
    product_category: "Laptop",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.51,
    key_features: ["card_visible", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Laptop_Specific_with_Card.png",
  },
  {
    filename: "TV_in_Home_with_Card_Benefits.png",
    display_name: "Smart TV — In-Home Lifestyle (1.91%)",
    creative_type: "Lifestyle",
    product_category: "TV",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.91,
    key_features: ["lifestyle_person", "card_visible", "single_product", "emi_per_month"],
    url: "/creatives/TV_in_Home_with_Card_Benefits.png",
  },
  {
    filename: "Samsung_Refrigerator_with_Card_Benifits.png",
    display_name: "Samsung Refrigerator — EMI + Cashback",
    creative_type: "Product Moment",
    product_category: "Refrigerator",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.45,
    key_features: ["card_visible", "cashback_visible", "brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/Samsung_Refrigerator_with_Card_Benifits.png",
  },
  {
    filename: "Refrigerator_Carousel_with_Card_Benifits.png",
    display_name: "Samsung + LG Refrigerator Carousel",
    creative_type: "Product Moment",
    product_category: "Refrigerator",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.14,
    key_features: ["cashback_visible", "multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/Refrigerator_Carousel_with_Card_Benifits.png",
  },
  {
    filename: "Air_Purifiers_Carousel_with_Card_Benifits.png",
    display_name: "Air Purifiers Carousel — Cashback",
    creative_type: "Product Moment",
    product_category: "Air Purifier",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.02,
    key_features: ["cashback_visible", "multi_product", "emi_per_month"],
    url: "/creatives/Air_Purifiers_Carousel_with_Card_Benifits.png",
  },
  {
    filename: "Air_Purifiers_with_Card_Benifits.png",
    display_name: "Air Purifiers — EMI + Card Benefits",
    creative_type: "Product Moment",
    product_category: "Air Purifier",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 0.24,
    key_features: ["card_visible", "cashback_visible", "brand_logo", "emi_per_month", "multi_product"],
    url: "/creatives/Air_Purifiers_with_Card_Benifits.png",
  },
  {
    filename: "Go_Pro_with_Card.png",
    display_name: "GoPro — Adventure on Easy EMI (2.50%)",
    creative_type: "Product Moment",
    product_category: "Camera",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.5,
    key_features: ["card_visible", "brand_logo", "affordability_messaging", "single_product"],
    url: "/creatives/Go_Pro_with_Card.png",
  },
  {
    filename: "Camera_with_Card.png",
    display_name: "Camera Lineup — Capture Moments (1.87%)",
    creative_type: "Product Moment",
    product_category: "Camera",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.87,
    key_features: ["card_visible", "brand_logo", "multi_product"],
    url: "/creatives/Camera_with_Card.png",
  },
  {
    filename: "Smartwatch_Carousel.png",
    display_name: "Smartwatch Carousel — EMI Options (1.53%)",
    creative_type: "Product Moment",
    product_category: "Wearable",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.53,
    key_features: ["emi_per_month", "multi_product"],
    url: "/creatives/Smartwatch_Carousel.png",
  },
  {
    filename: "Apple_Smartwatch_Cluster_with_Card_EMI_Benefits.png",
    display_name: "Apple Smartwatch — EMI Benefits",
    creative_type: "Product Moment",
    product_category: "Wearable",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 0.94,
    key_features: ["card_visible", "brand_logo", "emi_per_month", "multi_product"],
    url: "/creatives/Apple_Smartwatch_Cluster_with_Card_EMI_Benefits.png",
  },
  {
    filename: "Electronic_Cluster_with_Card_Benifits.png",
    display_name: "Electronic Cluster — Card Benefits (3.16%)",
    creative_type: "Card Spotlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 3.16,
    key_features: ["card_visible", "cashback_visible", "loan_limit_shown", "high_text_density", "multi_product"],
    url: "/creatives/Electronic_Cluster_with_Card_Benifits.png",
  },
  {
    filename: "Electronics_Cluster_with_Card_on_Stage.png",
    display_name: "Electronics Cluster — Card on Stage (1.57%)",
    creative_type: "Card Spotlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Card-Led"],
    reach_weighted_ctr: 1.57,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density", "multi_product"],
    url: "/creatives/Electronics_Cluster_with_Card_on_Stage.png",
  },
  {
    filename: "Electronic_Cluster_with_Card_in_Center_1.png",
    display_name: "Electronic Cluster — Card in Center v2 (1.45%)",
    creative_type: "Card Spotlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Card-Led"],
    reach_weighted_ctr: 1.45,
    key_features: ["card_visible", "loan_limit_shown", "multi_product"],
    url: "/creatives/Electronic_Cluster_with_Card_in_Center_1.png",
  },
  {
    filename: "Electronic_Cluster_with_Card_Benefits_Blue_CTA.png",
    display_name: "Electronics Cluster — Blue CTA (1.61%)",
    creative_type: "Offer Highlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Offer-Led", "Card-Led"],
    reach_weighted_ctr: 1.61,
    key_features: ["cashback_visible", "loan_limit_shown", "high_text_density", "multi_product"],
    url: "/creatives/Electronic_Cluster_with_Card_Benefits_Blue_CTA.png",
  },
  {
    filename: "Electronic_Cluster_with_Card_Benefits_Yellow_CTA.png",
    display_name: "Electronics Cluster — Yellow CTA (1.36%)",
    creative_type: "Offer Highlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Offer-Led", "Card-Led"],
    reach_weighted_ctr: 1.36,
    key_features: ["cashback_visible", "loan_limit_shown", "high_text_density", "multi_product"],
    url: "/creatives/Electronic_Cluster_with_Card_Benefits_Yellow_CTA.png",
  },
  {
    filename: "Electronic_Cluster_with_Card_in_Center.png",
    display_name: "Electronic Cluster — Card Activation",
    creative_type: "Card Spotlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Card-Led"],
    reach_weighted_ctr: 0.81,
    key_features: ["card_visible", "multi_product"],
    url: "/creatives/Electronic_Cluster_with_Card_in_Center.png",
  },
  {
    filename: "Electronic_Products_with_Card_in_Center.png",
    display_name: "Electronic Products — Card Center",
    creative_type: "Card Spotlight",
    product_category: "Electronics Cluster",
    goal_fit: ["Card-Led"],
    reach_weighted_ctr: 1.3,
    key_features: ["card_visible", "loan_limit_shown", "multi_product"],
    url: "/creatives/Electronic_Products_with_Card_in_Center.png",
  },
  {
    filename: "Electronics_Carousel_with_Card_Benifits.png",
    display_name: "Electronics Carousel — Card Benefits (1.16%)",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.16,
    key_features: ["emi_per_month", "multi_product", "high_text_density"],
    url: "/creatives/Electronics_Carousel_with_Card_Benifits.png",
  },
  {
    filename: "Electronic_Carousel_with_Card_Benifits.png",
    display_name: "Electronic Carousel — TV + Washing Machine",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.16,
    key_features: ["loan_limit_shown", "high_text_density", "multi_product"],
    url: "/creatives/Electronic_Carousel_with_Card_Benifits.png",
  },
  {
    filename: "Product_Specific_Carousel_with_Benifits.png",
    display_name: "Sony + Samsung Appliance Carousel",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.17,
    key_features: ["brand_logo", "emi_per_month", "multi_product", "high_text_density"],
    url: "/creatives/Product_Specific_Carousel_with_Benifits.png",
  },
  {
    filename: "People_Holding_up_Electronics.png",
    display_name: "People with Electronics — Lifestyle (1.13%)",
    creative_type: "Lifestyle",
    product_category: "Electronics Cluster",
    goal_fit: ["Card-Led", "Product-Led"],
    reach_weighted_ctr: 1.13,
    key_features: ["lifestyle_person", "card_visible", "multi_product"],
    url: "/creatives/People_Holding_up_Electronics.png",
  },
  {
    filename: "Gaming_Specific_Products_with_Card_in_Center.png",
    display_name: "Gaming Products — Card in Center (1.31%)",
    creative_type: "Card Spotlight",
    product_category: "Gaming",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.31,
    key_features: ["card_visible", "multi_product"],
    url: "/creatives/Gaming_Specific_Products_with_Card_in_Center.png",
  },
  // ─────────────────────────────────────────────────────────────────────────────
// NEW CREATIVE LIBRARY ENTRIES — paste into creativeLibrary.ts
// Source: WJ Campaign (Woh Jaane) performance data
// Note: WJ Camp CTRs are from interest-based targeting, not main acquisition
//       campaign. They run systematically lower than main portfolio (~1.0–2.2%
//       vs 2.12% median). Do not mix with main portfolio for signal analysis.
//       These entries are valid for vision reference matching but should not
//       be used in scenario routes until validated in acquisition context.
//
// DUPE FILES — no new entries needed, map to existing:
//   Realme_16_Pro.png         → Realme_16_Pro_Phone_with_Product_Specific_Card_Benefits.png
//   Redmi_Note_15_Pro.png     → Redmi_Note_15_Pro_Phone_with_Product_Specific_Card_Benefits.png
//   Oppo_A6_Pro.png           → Oppo_A6_pro_Product_with_Card_and_Benifits.png
//   Oppo_Reno_15C.png         → Oppo_Reno_15c_with_Card_and_Benifits.png
//   Laptop_Single_Product.png → Laptop_Specific_with_Card.png
//   Laptop_Multiple_Product.png → Multiple_Laptop_Specific_with_Card.png
//   iphone_car.png            → Apple_IPhone_Carousel.png
//   iPad.png                  → Ipad_Colours_with_Cards.png (confirm)
//
// EXCLUDED:
//   WJ_Camp_Video_Trip_Troop.png — video, excluded per v2 policy
//   Accessories_YT.png           — 3K reach, no signal
//   Ecom_Prod.png                — 10K reach, no signal
//   Product_Gif.png              — 5K reach, no signal
//   Product_Generic.png          — no CTR data provided
// ─────────────────────────────────────────────────────────────────────────────

  // ── AC / APPLIANCE ──────────────────────────────────────────────────────────

  {
    filename: "AC_Blue_Star.png",
    display_name: "Blue Star AC — EMI Benefits (1.24%)",
    creative_type: "Product Moment",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.24,
    key_features: ["brand_logo", "emi_per_month", "single_product", "high_text_density"],
    url: "/creatives/AC_Blue_Star.png",
  },
  {
    filename: "AC_Car_Multi_Brand.png",
    display_name: "AC Multi-Brand Carousel — EMI (1.70%)",
    creative_type: "Product Moment",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.70,
    key_features: ["multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/AC_Car_Multi_Brand.png",
  },
  {
    filename: "AC_Car_Voltas.png",
    display_name: "Voltas AC Carousel — EMI (1.30%)",
    creative_type: "Product Moment",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.30,
    key_features: ["brand_logo", "emi_per_month", "card_visible"],
    url: "/creatives/AC_Car_Voltas.png",
  },
  {
    filename: "AC_Cooler.png",
    display_name: "AC & Cooler — Category Benefits (1.10%)",
    creative_type: "Product Moment",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.10,
    key_features: ["multi_product", "emi_per_month"],
    url: "/creatives/AC_Cooler.png",
  },
  {
    filename: "Home_App_Car_Multi_Product.png",
    display_name: "Home Appliances Multi-Product Carousel (1.30%)",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.30,
    key_features: ["multi_product", "emi_per_month", "high_text_density"],
    url: "/creatives/Home_App_Car_Multi_Product.png",
  },
  {
    filename: "Home_App_Car_Voltas.png",
    display_name: "Voltas Home Appliance Carousel — Lifestyle (1.77%)",
    creative_type: "Lifestyle",
    product_category: "AC",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.77,
    key_features: ["brand_logo", "lifestyle_person", "emi_per_month", "card_visible"],
    url: "/creatives/Home_App_Car_Voltas.png",
  },

  // ── SMARTPHONES ─────────────────────────────────────────────────────────────

  {
    filename: "Android_Mobile_Car.png",
    display_name: "Android Mobile Carousel — Samsung + OnePlus (2.20%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 2.20,
    key_features: ["multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/Android_Mobile_Car.png",
  },
  {
    filename: "iPhone_15_17_Car.png",
    display_name: "Apple iPhone 15–17 Carousel — EMI (1.29%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.29,
    key_features: ["multi_product", "brand_logo", "emi_per_month", "card_visible"],
    url: "/creatives/iPhone_15_17_Car.png",
  },
  {
    filename: "iphone_car_multi_models.png",
    display_name: "Apple iPhone Multi-Model Carousel (1.10%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.10,
    key_features: ["multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/iphone_car_multi_models.png",
  },
  {
    filename: "Iphone_Prod_Car.png",
    display_name: "Apple iPhone Product Carousel — WJ Camp (1.10%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.10,
    key_features: ["multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/Iphone_Prod_Car.png",
  },
  {
    filename: "Mobile_UND_30K.png",
    display_name: "Smartphones Under ₹30K — Oppo + Samsung (1.75%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.75,
    key_features: ["cashback_visible", "brand_logo", "emi_per_month", "multi_product", "affordability_messaging"],
    url: "/creatives/Mobile_UND_30K.png",
  },
  {
    filename: "Nothing_4A.png",
    display_name: "Nothing Phone 4A — Easy EMI (0.98%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 0.98,
    key_features: ["brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Nothing_4A.png",
  },
  {
    filename: "Vivo_X300_FE.png",
    display_name: "Vivo X300 FE — Card + EMI (1.40%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.40,
    key_features: ["brand_logo", "emi_per_month", "single_product", "card_visible"],
    url: "/creatives/Vivo_X300_FE.png",
  },
  {
    filename: "Vivo_X300_Ultra.png",
    display_name: "Vivo X300 Ultra — EMI Benefits (1.50%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.50,
    key_features: ["brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/Vivo_X300_Ultra.png",
  },
  {
    filename: "WJ_Camp_Iphone_Prod_Car.png",
    display_name: "Apple iPhone Product Carousel — WJ Variant (1.10%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.10,
    key_features: ["multi_product", "brand_logo", "emi_per_month"],
    url: "/creatives/WJ_Camp_Iphone_Prod_Car.png",
  },
  {
    filename: "WJ_Camp_Realme_16_Pro_PF_16.png",
    display_name: "Realme 16 Pro PF16 — WJ Variant (1.65%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.65,
    key_features: ["brand_logo", "emi_per_month", "single_product"],
    url: "/creatives/WJ_Camp_Realme_16_Pro_PF_16.png",
  },
  {
    filename: "WJ_Camp_Samsung_S26.png",
    display_name: "Samsung S26 — Card + EMI Benefits (1.43%)",
    creative_type: "Product Moment",
    product_category: "Smartphone",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.43,
    key_features: ["brand_logo", "emi_per_month", "single_product", "card_visible"],
    url: "/creatives/WJ_Camp_Samsung_S26.png",
  },

  // ── CARD / OFFER ─────────────────────────────────────────────────────────────

  {
    filename: "Card_Face_BT.png",
    // LOW REACH: 1.75L — include but do not add to scenario routes
    display_name: "Card Face — BNPL Benefits (1.03%)",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led", "Offer-Led"],
    reach_weighted_ctr: 1.03,
    key_features: ["card_visible", "loan_limit_shown", "high_text_density"],
    url: "/creatives/Card_Face_BT.png",
  },
  {
    filename: "FK_1K_Offer.png",
    display_name: "Flipkart ₹1K Offer — Partner Benefits (1.10%)",
    creative_type: "Partner Co-branded",
    product_category: "Card",
    goal_fit: ["Offer-Led"],
    reach_weighted_ctr: 1.10,
    key_features: ["partner_logo", "cashback_visible", "card_visible"],
    url: "/creatives/FK_1K_Offer.png",
  },
  {
    filename: "Zero_Fee.png",
    display_name: "Zero Fee Offer — Card Benefits (0.90%)",
    creative_type: "Offer Highlight",
    product_category: "Card",
    goal_fit: ["Offer-Led", "Card-Led"],
    reach_weighted_ctr: 0.90,
    key_features: ["card_visible", "affordability_messaging", "loan_limit_shown"],
    url: "/creatives/Zero_Fee.png",
  },
  {
    filename: "Product_Gen_Card_Face.png",
    // LOW REACH: 2.33L — include but do not add to scenario routes
    display_name: "Product Generic — Card Face (0.95%)",
    creative_type: "Card Spotlight",
    product_category: "Card",
    goal_fit: ["Card-Led"],
    reach_weighted_ctr: 0.95,
    key_features: ["card_visible", "loan_limit_shown"],
    url: "/creatives/Product_Gen_Card_Face.png",
  },

  // ── GENERIC / ELECTRONICS CLUSTER ──────────────────────────────────────────

  {
    filename: "Generic_Product.png",
    display_name: "Generic Product — Multi-Category (0.87%)",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 0.87,
    key_features: ["multi_product", "card_visible"],
    url: "/creatives/Generic_Product.png",
  },
  {
    filename: "WJ_Camp_Generic_Product.png",
    display_name: "Generic Product — WJ Variant (0.63%)",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 0.63,
    key_features: ["multi_product"],
    url: "/creatives/WJ_Camp_Generic_Product.png",
  },
  {
    filename: "Product_Girl.png",
    display_name: "Girl with Electronics — Lifestyle Cluster (1.10%)",
    creative_type: "Lifestyle",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.10,
    key_features: ["lifestyle_person", "multi_product"],
    url: "/creatives/Product_Girl.png",
  },
  {
    filename: "Products_Gen_YT.png",
    display_name: "Generic Products — Yellow Thumbnail (0.83%)",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 0.83,
    key_features: ["multi_product", "high_text_density"],
    url: "/creatives/Products_Gen_YT.png",
  },

  // ── WEARABLE ─────────────────────────────────────────────────────────────────

  {
    filename: "SmartWatch_Car.png",
    // LOW REACH: 10K — include but do not add to scenario routes
    display_name: "Smartwatch Carousel — WJ Camp (1.70%)",
    creative_type: "Product Moment",
    product_category: "Wearable",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.70,
    key_features: ["multi_product", "emi_per_month"],
    url: "/creatives/SmartWatch_Car.png",
  },

  // ── LOW REACH (included for completeness, exclude from routing) ─────────────

  {
    filename: "Accessories_BT.png",
    // LOW REACH: 16K — no routing signal. Include for library completeness only.
    display_name: "Accessories — Bluetooth (1.00%)",
    creative_type: "Product Moment",
    product_category: "Electronics Cluster",
    goal_fit: ["Product-Led"],
    reach_weighted_ctr: 1.00,
    key_features: ["multi_product"],
    url: "/creatives/Accessories_BT.png",
  },
];


// ── PRE-FILTER FUNCTIONS ────────────────────────────────────────────────────

export function classifyProduct(input: string): ProductCategory {
  const l = input.toLowerCase();
  if (/(iphone|samsung|oneplus|oppo|vivo|realme|redmi|pixel|phone|smartphone|mobile)/.test(l))
    return 'Smartphone';
  if (/(laptop|macbook|dell|hp|lenovo|asus|notebook)/.test(l)) return 'Laptop';
  if (/(ipad|tablet)/.test(l)) return 'Tablet';
  if (/(tv|television|led|oled|crystal|smart.?tv)/.test(l)) return 'TV';
  if (/(ac|air.?con|voltas|cooling|split.?ac|air.?condition)/.test(l)) return 'AC';
  if (/(washing|washer|washing.?machine)/.test(l)) return 'Washing Machine';
  if (/(fridge|refrigerator)/.test(l)) return 'Refrigerator';
  if (/(camera|gopro|nikon|canon|sony.?cam|dslr|mirrorless)/.test(l)) return 'Camera';
  if (/(watch|smartwatch|wearable)/.test(l)) return 'Wearable';
  if (/(gaming|xbox|playstation|ps5|console|nintendo)/.test(l)) return 'Gaming';
  if (/(air.?purif)/.test(l)) return 'Air Purifier';
  if (/(card|card.?hero|card.?only|card.?spotlight|insta.?emi)/.test(l)) return 'Card';
  return 'Electronics Cluster';
}

// Extract brand keywords from manager input for brand-aware matching
function extractBrandKeywords(input: string): string[] {
  const brands = [
    'apple', 'iphone', 'ipad', 'samsung', 'oppo', 'vivo', 'realme',
    'redmi', 'oneplus', 'google', 'pixel', 'voltas', 'lg', 'flipkart',
    'amazon', 'sony', 'gopro', 'nikon', 'canon', 'hp', 'dell', 'lenovo',
  ];
  const l = input.toLowerCase();
  return brands.filter(b => l.includes(b));
}

export function getTopCreatives(
  productInput: string,
  intent: CreativeIntent,
  n = 5
): CreativeCard[] {
  const category = classifyProduct(productInput);

  // Card-Led intent: always pull from Card category regardless of product
  const categoryToFilter = intent === 'Card-Led' ? 'Card' : category;

  const allCategoryMatches = creativeLibrary
    .filter(c => c.goal_fit.includes(intent))
    .filter(c => c.product_category === categoryToFilter)
    .sort((a, b) => b.reach_weighted_ctr - a.reach_weighted_ctr);

  // Brand-aware: always surface brand-matching creatives first
  // e.g. "iPhone 16" → Apple/iPhone creatives appear before Samsung
  // This is intentional — reference images should be visually relevant,
  // not just highest CTR. CTR guidance comes from the knowledge base.
  const brandKeywords = extractBrandKeywords(productInput);
  const brandMatches = brandKeywords.length > 0
    ? allCategoryMatches.filter(c =>
        brandKeywords.some(k => c.display_name.toLowerCase().includes(k))
      )
    : [];

  const usedFilenames = new Set(brandMatches.map(c => c.filename));
  const categoryPad = allCategoryMatches
    .filter(c => !usedFilenames.has(c.filename))
    .slice(0, n - brandMatches.length);

  const result = [...brandMatches, ...categoryPad].slice(0, n);

  // If still short (rare edge case), pad with top non-cluster performers
  if (result.length < n) {
    const usedAll = new Set(result.map(c => c.filename));
    const globalPad = creativeLibrary
      .filter(c => c.goal_fit.includes(intent) && !usedAll.has(c.filename))
      .filter(c => c.product_category !== 'Electronics Cluster')
      .sort((a, b) => b.reach_weighted_ctr - a.reach_weighted_ctr)
      .slice(0, n - result.length);
    return [...result, ...globalPad];
  }

  return result;
}